<#
.SYNOPSIS
  Regenerates docs/interface-matrix.md and docs/test-results.md from live runs.

.DESCRIPTION
  Everything under docs/ that can be produced mechanically is produced here, so
  the documentation cannot drift away from what the binary actually reports.
  docs/findings.md is written by hand and is not touched.
#>
[CmdletBinding()]
param([string]$Exe)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $Exe) { $Exe = Join-Path $root 'build\vdprobe.exe' }
$docs = Join-Path $root 'docs'
New-Item -ItemType Directory -Force -Path $docs | Out-Null

if (-not (Test-Path $Exe)) { throw "vdprobe.exe not found at $Exe - run build.ps1 first" }

# ---- interface matrix (generated straight from the layout registry) ---------
& $Exe matrix | Set-Content -Path (Join-Path $docs 'interface-matrix.md') -Encoding utf8
Write-Host "wrote docs/interface-matrix.md"

# ---- test results (verbatim transcript of every subcommand) -----------------
$stamp = Get-Date -Format 'yyyy-MM-ddTHH:mm:sszzz'
$out = [System.Collections.Generic.List[string]]::new()
$out.Add('# Test results')
$out.Add('')
$out.Add("Generated by ``regen-docs.ps1`` on $stamp.")
$out.Add('')
$out.Add('Every block below is the verbatim stdout of the named subcommand on the')
$out.Add('probe host. Nothing is edited; the point is that the claims in')
$out.Add('`findings.md` can be checked against a transcript.')
$out.Add('')

$commands = @('system', 'monitors', 'windows', 'private-status', 'desktops',
              'current-desktop', 'per-monitor-status')
foreach ($c in $commands) {
    Write-Host "running: vdprobe $c"
    $text = (& $Exe $c 2>&1 | Out-String).TrimEnd()
    $code = $LASTEXITCODE
    $out.Add("## ``vdprobe $c``")
    $out.Add('')
    $out.Add("exit code: $code")
    $out.Add('')
    $out.Add('```text')
    $out.Add($text)
    $out.Add('```')
    $out.Add('')
}

$out | Set-Content -Path (Join-Path $docs 'test-results.md') -Encoding utf8
Write-Host "wrote docs/test-results.md"
